before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep tenace
  - sudo apt-get install -y gnulib
language: c
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - make

# vim:sw=2:
