dist: trusty
sudo: required
language: C
compiler:
  - gcc
  #- clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y debhelper libgtk2.0-dev libdds-dev intltool gnulib fakeroot
script:
  - ./autogen.sh
  - make
  - make distcheck
  - TAR=$(ls *.tar.*); TAR2=${TAR/-/_}; mv $TAR ../${TAR2/tar/orig.tar}
  - dpkg-buildpackage -uc -us
  - sudo apt-get install gnome-cards-data librsvg2-common
  - sudo dpkg -i ../tenace_*.deb

# vim:sw=2:
